sudo: true
dist: trusty
cache: false
env:
  global:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  - coreId=05i1N0000008OIeQAM
  - logicId=05i1N0000008OIoQAM
  - uiId=05i1N0000008OItQAM
  - securityId=05i1N0000008OIyQAM
before_install:
- openssl aes-256-cbc -K $encrypted_ca114f687cd3_key -iv $encrypted_ca114f687cd3_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
# The URL sfdx image now gives make and model in the folder, 
# so we create an 'sfdx' folder
# and we wget and unpack into that
# then install. (4 lines of comments to explain 3 lines of code)
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
# done unpacking the sfdx cli, on to other stuff like adding to path and using it
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
# SBOX stuff just for sandboxes, AFAIK
# - sfdx force:auth:jwt:grant -i $SBOXCONSUMERKEY -f assets/server.key -r https://test.salesforce.com  -u $SBOXUSERNAME
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human -w 30
- sfdx force:org:delete -u ciorg -p
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a pkgInstallOrg
- sfdx force:package:install -w 30 -u pkgInstallOrg -i $coreId
- sfdx force:package:install -w 30 -u pkgInstallOrg -i $logicId
- sfdx force:package:install -w 30 -u pkgInstallOrg -i $uiId
- sfdx force:package:install -w 30 -u pkgInstallOrg -i $securityId
#- sfdx force:package:install -w 30 -u $SBOXUSERNAME -i $coreId
#- sfdx force:package:install -w 30 -u $SBOXUSERNAME -i $logicId
#- sfdx force:package:install -w 30 -u $SBOXUSERNAME -i $uiId
#- sfdx force:package:install -w 30 -u $SBOXUSERNAME -i $securityId
- sfdx force:org:delete -u pkgInstallOrg -p
